local addonName = ...
local L = LibStub("AceLocale-3.0"):NewLocale(addonName, "zhCN", false)

if not L then return end

-- Vision
L["Anvil"] = "|cFFFFFFFF铁砧|r"
L["Anvil Note"] = "|cFFDC143C虚铸骏马的缰绳:|r 需要4层被诅咒的马蹄铁增益并至少装备1个面具。|cFFa335ee虚铸骏马的缰绳|r"
L["Cursed Horseshoe"] = "|cFFFFFFFF被诅咒的马蹄铁|r"
L["Cursed Horseshoe Note"] = "收集4个被诅咒的马蹄铁，至少|cFFDC143C装备1个面具|r以获得|cFFa335ee虚铸骏马的缰绳|r"
L["Magic-Lined Manifold"] = "|cFFFFFFFF魔法内衬集管|r"
L["Magic-Lined Manifold Note"] = "|cFFDC143C亡命摩托排气系统:|r 需装备|cFF0070DD至少1个面具|r 在拍卖行入口附近拾取箱子。|cFFa335ee虚空之火亡命摩托|r"
L["Trash"] = "|cFFFFFFFF废料|r"
L["Trash Note"] = "|cFFDC143C筑巢的群聚虫:|r 有概率召唤稀有怪物。|cFFa335ee筑巢的群聚虫|r"
L["Black Blood Bar"] = "|cFFFFFFFF黑血锭|r"
L["Black Blood Bar Note"] = "|cFFDC143C黑血灌注之锭:|r 制造|cFFa335ee虚空水晶豹|r的原料"
L["Ripped Note"] = "|cFFFFFFFF虚痕狮鹫的缰绳|r"
L["Ripped Note Note"] = "你必须有至少|cFFDC143C2个激活的面具|r。\n\n击杀审判官达克斯比，然后在楼梯上阅读“被撕破的便笺”提供的线索，接着在水井(65.7, 71.6)阅读另一个线索（会提示食物是生的还是熟的）R - 生食 C - 熟食。\n\n1. 挑食的家伙只想吃鱼 - |cFF0070DD1x鲜鱼片（生） 1x串烧鱼片（熟）|r\n\n2. 挑食的家伙只想吃菌类 - |cFF0070DD1x被斩断的菌丝花（生） 1x炙烤菌丝花（熟）|r\n\n3. 挑食的家伙只想吃香料腌制的肉 - |cFF0070DD1x香肉贮藏（生） 1x朴素炖煮（熟）|r\n\n4. 挑食的家伙只想吃牛排 - |cFF0070DD1x分切的肉排（生） 1x未风干的野地肉排（熟）|r\n\n将所需食物放入“布满爪痕的碗”并选择“摇晃食盆”。|cFFa335ee虚痕狮鹫的缰绳|r"
L["Big Keech"] = "|cFFFFFFFF大块头齐奇|r"
L["Big Keech Note"] = "掉落|cFF0070DD虚空束缚神秘宝珠|r(全员)和|cFF0070DD图鉴：虚空水晶猎豹|r(珠宝工匠专属)，用于制造|cFFa335ee虚空水晶猎豹|r"
L["Wolf Saddle"] = "|cFFFFFFFF狼皮鞍座|r"
L["Wolf Saddle Note"] = "需装备|cFF0070DD至少1个面具|r，拾取物品（位于拍卖行大楼内，拍卖师右侧的地面上。）。|cFFa335ee虚痕狼母的缰绳|r"
L["Wolf Tack"] = "|cFFFFFFFF座狼用具包|r"
L["Wolf Tack Note"] = "需装备|cFF0070DD至少1个面具，|r。拾取物品（位于主帐篷建筑旁边，虚狂巨兽身后。）。|cFFa335ee虚痕狼母的缰绳|r"
L["Wolf Rug"] = "|cFFFFFFFF狼皮毯|r"
L["Wolf Rug Note"] = "需装备|cFF0070DD至少1个面具|r。收集齐狼鞍和狼具（获得破烂的狼骑兵装备增益），激活狼皮毯获得|cFFa335ee虚痕狼母的缰绳|r"
L["Valley of Wisdom Elevator"] = "|cFFFFFFFF虚痕驭风者的缰绳|r"
L["Valley of Wisdom Elevator Note"] = "需装备|cFF0070DD至少2个面具|r，清空智慧谷，乘坐电梯至顶层，击杀一些虚痕幼崽，直到稀有的虚痕双足飞龙主母出现。击杀后获得|cFFa335ee虚痕驭风者的缰绳|r"
L["Gain"] = "|cFFFFFFFF熊之魂|r"
L["Gain Note"] = "急速提高 10%。"
L["Gain 2"] = "|cFFFFFFFF回恩壁垒|r"
L["Gain 2 Note"] = "全能提高 7%。"
L["Gain 3"] = "|cFFFFFFFF强化|r"
L["Gain 3 Note"] = "造成伤害提高 10%。"
L["Gain 4"] = "|cFFFFFFFF浓缩|r"
L["Gain 4 Note"] = "爆击几率提高 10%。"
L["Gain 5"] = "|cFFFFFFFF禁酒|r"
L["Gain 5 Note"] = "生命值提高10%。"
L["Gain 6"] = "|cFFFFFFFF风之魂|r"
L["Gain 6 Note"] = "急速提高10%。 移动速度提高10%。"
L["Gain 7"] = "|cFFFFFFFF虚灵精华|r"
L["Gain 7 Note"] = "爆击几率提高10%。"
L["Gain 8"] = "|cFFFFFFFF铁匠之力|r"
L["Gain 8 Note"] = "所有伤害提高10%。"
L["Void-Forged Engine Block"] = "|cFFFFFFFF虚铸直列四缸发动机|r"
L["Void-Forged Engine Block Note"] = "|cFFDC143C虚铸引擎机体：|r 需装备|cFF0070DD至少1个面具，在暗巷区的工程车间的桌子上拾取。 |cFFa335ee虚空之火亡命摩托|r"
L["Poisons"] = "|cFFFFFFFF毒药|r"
L["Poisons Note"] = "这是一种会降低理智且不要饮用的坏药水。"

-- Waypoints
L["Create waypoint"] = "创建路径点"
L["Create all waypoints"] = "创建所有路径点"
L["Hide node"] = "隐藏节点"
L["Close"] = "关闭"

-- Options
L["Icon settings"] = "图标设置"
L["These settings control the look of the icon."] = "这些设置控制图标外观"
L["Icon Scale"] = "图标缩放"
L["The scale of the icons"] = "图标的大小比例"
L["Icon Alpha"] = "图标透明度"
L["The alpha transparency of the icons"] = "图标的透明程度"
L["World Map"] = "世界地图"
L["Show icons on world map"] = "在世界地图显示图标"
L["Minimap"] = "小地图"
L["Show icons on the minimap"] = "在小地图显示图标"
L["What to display"] = "显示内容"
L["Show Zamros"] = "显示金币获取点"
L["Show Zamros gold"] = "显示可获得金币的活动点"
L["Reset hidden nodes"] = "重置隐藏节点"
L["Show all nodes that you manually hid by right-clicking on them and choosing \"hide\"."] = "显示所有通过右键点击选择'隐藏'的手动隐藏节点"
